version: '3'

services:
    node:
        container_name: webgl-final
        build: .
        command: npm run serverstart
        ports:
            -   "3000:3000"
        volumes:
            -   .:/usr/src/app
            -   /usr/src/app/node_modules
